### PR TITLE
Specify limits on provider versions

### PR DESCRIPTION
**Pull request by thomasleese**
Using the `~>` operator means the minor version will stay up to date, but avoids us upgrading the major version which may have breaking changes.

### CODE REVIEW

**Comment by saliceti** [comment]
I'm not sure about this change. [According to hashicorp](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#terraform-core-and-provider-versions), the best practice is:
>  Reusable modules should constrain only their minimum allowed versions of Terraform and providers, such as >= 0.12.0. This helps avoid known incompatibilities, while allowing the user of the module flexibility to upgrade to newer versions of Terraform without altering the module.

> Root modules should use a ~> constraint to set both a lower and upper bound on versions for each provider they depend on.

**Comment by thomasleese** [comment]
> I'm not sure about this change. [According to hashicorp](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#terraform-core-and-provider-versions), the best practice is:
> 
> > ...

I don't quite understand that guidance. If we leave the constraints as we've got them in here, it opens us up to our modules being incompatible with a version of a provider we claim to be compatible with (assuming Terraform providers follow semantic versioning).

For example, the Azure provider could be updated with a breaking change, and they release version 3.0.0. With the current version constraints we're claiming to be compatible with this hypothetical 3.0.0 release when that wouldn't necessarily be true. It doesn't seem right to require the users of our modules to put in their own constraints, our modules should own which versions of the providers they're compatible with.

In that example, this PR will not allow any user of our modules to upgrade to version 3.0.0 without us first checking it's compatible with the code in this repo, reducing the risk of unintended breakages.

It seems backwards to me to require the users of these modules to each have to put in their own version constraints when ideally these modules should be opaque for the most part - they should work out the box without requiring much thought.

**Comment by saliceti** [comment]
> > I'm not sure about this change. [According to hashicorp](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#terraform-core-and-provider-versions), the best practice is:
> > > ...
> 
> I don't quite understand that guidance. If we leave the constraints as we've got them in here, it opens us up to our modules being incompatible with a version of a provider we claim to be compatible with (assuming Terraform providers follow semantic versioning).

The actual version is not set by the module, but by the caller. So we shouldn't suffer from a breaking change unless we are actually testing it. Then we could add "<=" version constraint in this case. Until we fix the module.

This is fairly well explained here: https://discuss.hashicorp.com/t/best-practice-where-should-i-set-the-provider-version/1986/2

**Comment by thomasleese** [comment]
> The actual version is not set by the module, but by the caller. So we shouldn't suffer from a breaking change unless we are actually testing it. Then we could add "<=" version constraint in this case. Until we fix the module.

This is true, in that the lock file is generated for the root module, but the versions constraints are merged from all the modules. I'm struggling to see the benefit of putting version constraints in each of the callers.

Especially if, in a worst case scenario where there's a breaking change in a minor version bump and we're forced to add a constraint `<= x.x.x.` in these modules, we are still relying on the constraints in these modules - not the constraints we've put in the callers.

> This is fairly well explained here: https://discuss.hashicorp.com/t/best-practice-where-should-i-set-the-provider-version/1986/2

I interpret this guidance as being concerned over third party shared modules having overly restrictive version constraints and then preventing callers from using newer versions. I suspect the risk of this is low with us given that we own both these modules and the callers, and for the most part the callers will be relying entirely on the functionality in these modules rather than using them in combination with the providers directly.

From that explanation:

> > If a particular shared module is known not to work after a certain provider version – perhaps due to breaking changes in the provider that the module author does not tend to accommodate yet – then the shared module might also temporarily specify a < constraint to record that.

I think I'm looking at it from the opposite angle to this. Rather than waiting to see if we may be incompatible with a future major version bump (with `>=` and then a temporary `<`), I'm saying we should assume that a future major version will be incompatible (because we don't know any better) and use `~>`. When we come to need to use a feature from a newer major version, we can then upgrade the modules to be compatible. I'd prefer us to be more restrictive, prevent accidentally blocking/breaking deploys, than being less restrictive, but running the risk of unexpected breakages.

Of course, we can use `~>` in the callers to prevent accidentally blocking/breaking deploys on major version bumps, but I don't see why we're pushing the responsibility on them (and thus having to record the version constraint in three places - our modules, the caller root modules and the lock files).

Imagine if one of the providers we use is updated with breaking changes, eventually we update the modules to be compatible and we change the version constraint to `>= 3.0.0`. All of the users of these modules are then forced to update their own version constraints to `~> 3.0.0` (because `~> 2.x.x` would conflict with `>= 3.0.0`). This feels like an unnecessary burden to me, and doesn't add any benefits.

**Comment by thomasleese** [comment]
Replaced by #59.

**Pull request closed without merging**
